name: 14-django-upgraded
channels:
  - conda-forge
dependencies:
  - python=3.14
  - django>=4.2.24,<5
  - djangorestframework>=3.15.2
  - sqlparse>=0.5
  - psycopg>=3.2
  - gunicorn>=23
  - pillow>=11
platforms:
  - linux-64
  - osx-arm64
