repos:
  - repo: https://github.com/compilerla/conventional-pre-commit
    rev: v4.4.0
    hooks:
      - id: conventional-pre-commit
        stages: [commit-msg]
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: check-yaml
      - id: check-toml
      - id: check-merge-conflict
  - repo: local
    hooks:
      - id: rustfmt
        name: rustfmt
        entry: pixi run cargo fmt --
        language: system
        types: [rust]
        pass_filenames: false
      - id: clippy
        name: clippy
        entry: pixi run cargo clippy --all-targets -- -D warnings
        language: system
        types: [rust]
        pass_filenames: false
      - id: taplo
        name: taplo
        entry: pixi run taplo format
        language: system
        types: [toml]
      - id: typos
        name: typos
        entry: pixi run typos
        language: system
        pass_filenames: false
