"""Regenerate data/cran.toml: how conda-forge's r-* packages are named on CRAN (#436).

Most r-* packages are the CRAN package of the same name, lower-cased (r-ggplot2 is ggplot2), and
need no entry. The table holds the rest: names CRAN spells with capitals (r-rcpp is Rcpp), and
r-* packages that were never on CRAN, current or archived (r-base, r-catboost), which get no
CRAN purl. It is a fallback: a package's own DESCRIPTION file, when one is on disk, wins.

    pixi run cran-table             # rewrite data/cran.toml
    pixi run cran-table --check     # exit 1 if it is out of date
"""

from __future__ import annotations

import argparse
import json
import re
import sys
import urllib.request
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
TABLE = ROOT / "data" / "cran.toml"
CRAN_PACKAGES = "https://cran.r-project.org/src/contrib/PACKAGES"
CRAN_ARCHIVE = "https://cran.r-project.org/src/contrib/Archive/"
CHANNELDATA = "https://conda.anaconda.org/conda-forge/channeldata.json"

HEADER = """\
# How conda-forge's r-* packages are named on CRAN. Generated by scripts/cran_table.py from CRAN's
# package list and archive and conda-forge's channel data; do not edit by hand.
#
# An r-* package not listed here is the CRAN package of the same name without the `r-` prefix
# (r-ggplot2 is ggplot2). [renamed] lists the ones CRAN spells differently, [not-cran] the ones
# that were never on CRAN, which get no CRAN purl. A package's own DESCRIPTION file, read from an
# installed environment or the package cache, wins over this table.
"""


def get(url: str) -> bytes:
    """GET a URL."""
    request = urllib.request.Request(url, headers={"User-Agent": "pixi-sbom-cran-table"})
    with urllib.request.urlopen(request, timeout=120) as response:
        return response.read()


def cran_names(packages: str, archive: str) -> dict[str, str]:
    """Every CRAN package name, current or archived, keyed by its lower-cased spelling."""
    names = set(re.findall(r"^Package: (\S+)", packages, re.M))
    names |= set(re.findall(r'href="([A-Za-z0-9.]+)/"', archive))
    by_lower: dict[str, str] = {}
    for name in sorted(names):
        by_lower.setdefault(name.lower(), name)
    return by_lower


def table(conda_names: list[str], cran: dict[str, str]) -> tuple[dict[str, str], list[str]]:
    """The entries: r-* names CRAN spells differently, and r-* names CRAN never had."""
    renamed, not_cran = {}, []
    for name in sorted(n for n in conda_names if n.startswith("r-")):
        real = cran.get(name[2:])
        if real is None:
            not_cran.append(name)
        elif real != name[2:]:
            renamed[name] = real
    return renamed, not_cran


def render(renamed: dict[str, str], not_cran: list[str]) -> str:
    """The TOML file."""
    lines = [HEADER, "[renamed]"]
    lines += [f'"{name}" = "{real}"' for name, real in sorted(renamed.items())]
    lines += ["", "[not-cran]", "names = ["]
    lines += [f'  "{name}",' for name in sorted(not_cran)]
    lines += ["]", ""]
    return "\n".join(lines)


def main(argv: list[str] | None = None) -> int:
    """Fetch the lists and write, or check, the table."""
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument("--check", action="store_true", help="exit 1 if data/cran.toml is out of date")
    args = parser.parse_args(argv)
    cran = cran_names(get(CRAN_PACKAGES).decode(), get(CRAN_ARCHIVE).decode())
    conda = list(json.loads(get(CHANNELDATA))["packages"])
    text = render(*table(conda, cran))
    if args.check:
        current = TABLE.read_text(encoding="utf-8") if TABLE.exists() else ""
        if current != text:
            sys.stderr.write("data/cran.toml is out of date: run `pixi run cran-table`\n")
            return 1
        return 0
    TABLE.write_text(text, encoding="utf-8")
    renamed, not_cran = table(conda, cran)
    sys.stderr.write(f"{len(renamed)} renamed, {len(not_cran)} not on CRAN\n")
    return 0


if __name__ == "__main__":
    sys.exit(main())
