//! A fully pinned `requirements.txt`, read as the lock it is: what `pip-compile --generate-hashes`
//! and `uv pip compile` write. Every requirement is `name==version`, optionally with
//! `--hash=sha256:` lines and an environment marker, so nothing is resolved; a file with a range
//! (or a URL, a path, an editable install) is refused with the command that makes a lock of it.
//!
//! The graph comes from the `# via` comments pip-compile and uv write under each requirement:
//! `# via requests` is an edge from requests, and `# via -r requirements.in` marks a requirement
//! the project asked for itself. The file covers one interpreter; pip-compile names it in its
//! header (`autogenerated by pip-compile with Python 3.13`), which is what markers are evaluated
//! for.

use std::collections::{BTreeMap, BTreeSet};
use std::path::{Path, PathBuf};
use std::str::FromStr;

use miette::Diagnostic;
use pep508_rs::{MarkerTree, Requirement, VerbatimUrl};
use thiserror::Error;

use crate::model::{Package, PackageKind, Root, Sbom, Supplier};
use crate::purl;

/// The index a file names none of.
const DEFAULT_INDEX: &str = "https://pypi.org/simple";
/// The Python markers are evaluated for when the file does not say.
const FALLBACK_PYTHON: &str = "3.14";

/// Errors from reading a requirements file.
#[derive(Debug, Error, Diagnostic)]
pub enum RequirementsError {
    /// The file (or one it includes with `-r` / `-c`) could not be read.
    #[error("cannot read {path}")]
    #[diagnostic(code(pixi_sbom::requirements::read))]
    Read {
        path: String,
        #[source]
        source: std::io::Error,
    },

    /// A requirement that is not pinned to one version.
    #[error("line {line} of {path} is not pinned to one version: {text}")]
    #[diagnostic(
        code(pixi_sbom::requirements::not_pinned),
        help(
            "pixi-sbom reads a lock and never resolves one; make this file a lock with \
             `uv pip compile {path} -o pylock.toml` (then pass pylock.toml), or \
             `pip-compile --generate-hashes {path}` (then pass what it writes)"
        )
    )]
    NotPinned { path: String, line: usize, text: String },

    /// A line that cannot be parsed as a requirement.
    #[error("line {line} of {path} is not a requirement: {text}")]
    #[diagnostic(code(pixi_sbom::requirements::parse), help("{message}"))]
    Parse {
        path: String,
        line: usize,
        text: String,
        message: String,
    },

    /// The platform has no marker environment this reader knows.
    #[error(transparent)]
    #[diagnostic(transparent)]
    Markers(#[from] crate::pylock::PylockError),

    /// A package name the purl spec rejects.
    #[error(transparent)]
    #[diagnostic(transparent)]
    Purl(#[from] purl::PurlError),
}

/// One pinned requirement.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct Pin {
    pub name: String,
    pub version: String,
    /// The marker as written, when there is one.
    pub marker: Option<String>,
    /// `sha256` digests from `--hash` options; pip accepts any of them.
    pub sha256: Vec<String>,
    /// Names from the `# via` comments: the packages that need this one.
    pub via: Vec<String>,
    /// `# via -r <file>`: the project asked for it.
    pub declared: bool,
}

/// A parsed requirements file and the files it includes.
#[derive(Debug, Clone, Default)]
pub struct Requirements {
    pub pins: Vec<Pin>,
    /// `--index-url` / `-i`, when the file names one.
    pub index_url: Option<String>,
    /// The interpreter the file was compiled for, from pip-compile's header.
    pub python: Option<String>,
}

/// A parsed file, with the text it was parsed from.
#[derive(Debug)]
pub struct Loaded {
    pub requirements: Requirements,
    pub contents: String,
}

/// Whether the file at `path` looks like a requirements file rather than a lockfile of another
/// kind: plain lines of requirements and pip options, no TOML table, YAML document or JSON. Only
/// the start is read. A file named for requirements counts whatever it pins, so one with ranges
/// is refused with the command that locks it; any other `.txt` or `.in` file must pin something,
/// or a text file that merely starts with a word would be taken for one. Whether every line is
/// pinned is for reading to say.
pub fn is_requirements(path: &Path) -> bool {
    use std::io::{BufRead, BufReader};
    let name = path.file_name().and_then(|n| n.to_str()).unwrap_or("");
    if !(name.ends_with(".txt") || name.ends_with(".in") || name.contains("requirements")) {
        return false;
    }
    let Ok(file) = std::fs::File::open(path) else {
        return false;
    };
    let named = name.contains("requirements");
    let mut saw_requirement = false;
    let mut saw_pin = false;
    for line in BufReader::new(file).lines().take(200).map_while(Result::ok) {
        let line = line.trim();
        if line.is_empty() || line.starts_with('#') || line.starts_with("--hash") {
            continue;
        }
        if line == "@EXPLICIT" || line.starts_with('[') || line.starts_with('{') || line.starts_with("---") {
            return false;
        }
        if line.starts_with('-') {
            continue;
        }
        let first = line.chars().next().unwrap_or(' ');
        if !(first.is_ascii_alphanumeric()) {
            return false;
        }
        saw_requirement = true;
        saw_pin |= line.contains("==");
    }
    saw_requirement && (named || saw_pin)
}

/// Read and parse the file at `path`, following `-r` and `-c` includes.
pub fn load(path: &Path) -> Result<Loaded, RequirementsError> {
    let contents = std::fs::read_to_string(path).map_err(|source| RequirementsError::Read {
        path: path.display().to_string(),
        source,
    })?;
    let mut requirements = Requirements::default();
    let mut seen = BTreeSet::new();
    parse_into(&contents, path, &mut requirements, &mut seen)?;
    Ok(Loaded { requirements, contents })
}

/// Parse text that came from `path` (for its includes and its messages).
pub fn parse(contents: &str, path: &Path) -> Result<Requirements, RequirementsError> {
    let mut requirements = Requirements::default();
    parse_into(contents, path, &mut requirements, &mut BTreeSet::new())?;
    Ok(requirements)
}

/// Logical lines: `\\` continuations joined, with each one's first physical line number.
fn logical_lines(contents: &str) -> Vec<(usize, String)> {
    let mut out = Vec::new();
    let mut current = String::new();
    let mut start = 0;
    for (i, raw) in contents.lines().enumerate() {
        if current.is_empty() {
            start = i + 1;
        }
        match raw.trim_end().strip_suffix('\\') {
            Some(head) => {
                current.push_str(head);
                current.push(' ');
            }
            None => {
                current.push_str(raw);
                out.push((start, std::mem::take(&mut current)));
            }
        }
    }
    if !current.is_empty() {
        out.push((start, current));
    }
    out
}

fn parse_into(
    contents: &str,
    path: &Path,
    out: &mut Requirements,
    seen: &mut BTreeSet<PathBuf>,
) -> Result<(), RequirementsError> {
    seen.insert(path.to_path_buf());
    let origin = path.display().to_string();
    if out.python.is_none() {
        out.python = contents.lines().take(10).find_map(|line| {
            let rest = line.split("autogenerated by pip-compile with Python ").nth(1)?;
            Some(rest.split_whitespace().next()?.to_string())
        });
    }
    // `# via` comments follow the requirement they describe, on lines of their own.
    let mut last: Option<usize> = None;
    let mut in_via = false;
    for (line, text) in logical_lines(contents) {
        let trimmed = text.trim();
        if let Some(comment) = trimmed.strip_prefix('#') {
            let comment = comment.trim();
            let Some(index) = last else { continue };
            let names = if let Some(rest) = comment.strip_prefix("via") {
                in_via = true;
                rest.trim().to_string()
            } else if in_via {
                comment.to_string()
            } else {
                continue;
            };
            if names.is_empty() {
                continue;
            }
            // `-r requirements.in`, `-c constraints.txt`, or a dependent's name.
            if names.starts_with("-r ") || names.starts_with("-c ") || names.starts_with("--requirement") {
                out.pins[index].declared = true;
            } else if let Some(name) = names.split_whitespace().next() {
                out.pins[index].via.push(name.to_string());
            }
            continue;
        }
        in_via = false;
        // A trailing comment on a requirement line.
        let body = match trimmed.find(" #") {
            Some(at) => trimmed[..at].trim(),
            None => trimmed,
        };
        if body.is_empty() {
            continue;
        }
        if let Some(option) = body.strip_prefix('-') {
            include_or_option(option, &origin, path, line, body, out, seen)?;
            continue;
        }
        // The requirement, then its `--hash` options.
        let (requirement, options) = match body.find(" --") {
            Some(at) => (&body[..at], &body[at..]),
            None => (body, ""),
        };
        let parsed = Requirement::<VerbatimUrl>::from_str(requirement).map_err(|err| RequirementsError::Parse {
            path: origin.clone(),
            line,
            text: requirement.to_string(),
            message: err.to_string(),
        })?;
        let pinned = pinned_version(&parsed).ok_or_else(|| RequirementsError::NotPinned {
            path: origin.clone(),
            line,
            text: requirement.to_string(),
        })?;
        let sha256 = options
            .split_whitespace()
            .filter_map(|o| {
                o.strip_prefix("--hash=sha256:")
                    .or_else(|| o.strip_prefix("--hash=SHA256:"))
            })
            .map(str::to_lowercase)
            .collect();
        let marker = requirement
            .split_once(';')
            .map(|(_, m)| m.trim().to_string())
            .filter(|m| !m.is_empty());
        out.pins.push(Pin {
            name: parsed.name.to_string(),
            version: pinned,
            marker,
            sha256,
            via: Vec::new(),
            declared: false,
        });
        last = Some(out.pins.len() - 1);
    }
    Ok(())
}

/// The one version an `==` (or `===`) specifier pins; `None` for anything else.
fn pinned_version(requirement: &Requirement<VerbatimUrl>) -> Option<String> {
    let pep508_rs::VersionOrUrl::VersionSpecifier(specifiers) = requirement.version_or_url.as_ref()? else {
        return None;
    };
    let mut iter = specifiers.iter();
    let specifier = iter.next()?;
    if iter.next().is_some() {
        return None;
    }
    let text = specifier.to_string();
    let version = text.strip_prefix("===").or_else(|| text.strip_prefix("=="))?;
    (!version.contains('*')).then(|| version.trim().to_string())
}

/// A `-r` / `-c` include, an index option, or another pip option (ignored). An editable install
/// is refused: it names a checkout, not a release.
fn include_or_option(
    option: &str,
    origin: &str,
    path: &Path,
    line: usize,
    body: &str,
    out: &mut Requirements,
    seen: &mut BTreeSet<PathBuf>,
) -> Result<(), RequirementsError> {
    let (flag, value) = match option.split_once(['=', ' ']) {
        Some((flag, value)) => (flag.trim(), value.trim()),
        None => (option.trim(), ""),
    };
    match flag {
        "r" | "-requirement" | "c" | "-constraint" => {
            let included = path.parent().unwrap_or(Path::new(".")).join(value);
            if seen.contains(&included) {
                return Ok(());
            }
            let text = std::fs::read_to_string(&included).map_err(|source| RequirementsError::Read {
                path: included.display().to_string(),
                source,
            })?;
            parse_into(&text, &included, out, seen)
        }
        "i" | "-index-url" => {
            out.index_url = Some(value.to_string());
            Ok(())
        }
        "e" | "-editable" => Err(RequirementsError::NotPinned {
            path: origin.to_string(),
            line,
            text: body.to_string(),
        }),
        _ => Ok(()),
    }
}

/// Build the document model for `platform` (`None` = the host).
pub fn build_sbom(
    requirements: &Requirements,
    platform: Option<&str>,
    root: Root,
    file_name: &str,
) -> Result<Sbom, RequirementsError> {
    let platform = match platform {
        Some(name) => name.to_string(),
        None => rattler_conda_types::Platform::current()
            .map(|p| p.to_string())
            .unwrap_or_else(|| "linux-64".to_string()),
    };
    let python = requirements
        .python
        .clone()
        .unwrap_or_else(|| FALLBACK_PYTHON.to_string());
    let env = crate::pylock::marker_environment(&platform, &python)?;
    let index = requirements
        .index_url
        .clone()
        .unwrap_or_else(|| DEFAULT_INDEX.to_string());
    let supplier = Supplier {
        name: crate::pylock::url_host(&index).unwrap_or_else(|| index.clone()),
        url: Some(index.clone()),
    };

    // Later pins of a name (an include repeating one) do not add a second package.
    let mut by_name: BTreeMap<String, &Pin> = BTreeMap::new();
    for pin in &requirements.pins {
        if let Some(marker) = &pin.marker
            && let Ok(tree) = MarkerTree::from_str(marker)
            && !tree.evaluate(&env, &[])
        {
            continue;
        }
        by_name.entry(purl::normalize_pypi_name(&pin.name)).or_insert(pin);
    }
    let ids: BTreeMap<String, String> = by_name
        .iter()
        .map(|(name, pin)| Ok((name.clone(), purl::pypi(&pin.name, &pin.version)?)))
        .collect::<Result<_, purl::PurlError>>()?;
    // `# via a` on b is an edge a -> b.
    let mut edges: BTreeMap<String, BTreeSet<String>> = BTreeMap::new();
    for (name, pin) in &by_name {
        for dependent in &pin.via {
            let dependent = purl::normalize_pypi_name(dependent);
            if ids.contains_key(&dependent) && dependent != *name {
                edges.entry(dependent).or_default().insert(ids[name].clone());
            }
        }
    }
    let mut packages: Vec<Package> = by_name
        .iter()
        .map(|(name, pin)| {
            let mut properties = BTreeMap::new();
            properties.insert("pixi:index-url".to_string(), index.clone());
            if let Some(marker) = &pin.marker {
                properties.insert("pixi:marker".to_string(), marker.clone());
            }
            if pin.declared {
                properties.insert(crate::manifest::DIRECT_PROPERTY.to_string(), "true".to_string());
                properties.insert(crate::manifest::DECLARED_IN_PROPERTY.to_string(), "default".to_string());
            }
            Package {
                id: ids[name].clone(),
                name: pin.name.clone(),
                version: Some(pin.version.clone()),
                kind: PackageKind::Pypi,
                purl: ids[name].clone(),
                supplier: Some(supplier.clone()),
                extra_purls: Vec::new(),
                purls_from_lock: false,
                location: String::new(),
                sha256: pin.sha256.first().cloned(),
                md5: None,
                license: None,
                license_files: Vec::new(),
                description: None,
                homepage: None,
                repository: None,
                documentation: None,
                yanked: None,
                properties,
                dependencies: edges.remove(name).map(|d| d.into_iter().collect()).unwrap_or_default(),
            }
        })
        .collect();
    packages.sort_by(|a, b| a.sort_key().cmp(&b.sort_key()));
    // pip-compile's `# via -r` names what the project asked for; with that, the root depends on
    // exactly those, as for a manifest beside a lockfile.
    let declared_roots = packages
        .iter()
        .any(|p| p.properties.contains_key(crate::manifest::DIRECT_PROPERTY));
    tracing::info!(
        platform = %platform,
        python = %python,
        packages = packages.len(),
        "read the requirements file"
    );
    Ok(Sbom {
        root,
        environment: "default".to_string(),
        platform,
        lockfile: file_name.to_string(),
        prefix: None,
        document: None,
        packages,
        vulnerabilities: Vec::new(),
        excluded: Vec::new(),
        declared_missing: Vec::new(),
        incomplete: crate::model::Incomplete::default(),
        lifecycles: vec![crate::model::PHASE_LOCKFILE.into()],
        declared_roots,
        scopes: BTreeMap::new(),
        interpreter: None,
    })
}

#[cfg(test)]
mod tests {
    use super::*;

    const COMPILED: &str = "#
# This file is autogenerated by pip-compile with Python 3.13
# by the following command:
#
#    pip-compile --generate-hashes requirements.in
#
--index-url https://mirror.example/simple

certifi==2026.7.22 \\
    --hash=sha256:AA \\
    --hash=sha256:bb
    # via requests
idna==3.20 \\
    --hash=sha256:cc
    # via requests
pywin32==311 ; sys_platform == 'win32' \\
    --hash=sha256:dd
    # via -r requirements.in
requests==2.32.3 \\
    --hash=sha256:ee
    # via
    #   -r requirements.in
    #   other
";

    fn sbom(text: &str, platform: &str) -> Sbom {
        let parsed = parse(text, Path::new("requirements.txt")).unwrap();
        build_sbom(&parsed, Some(platform), Root::default(), "requirements.txt").unwrap()
    }

    #[test]
    fn pins_hashes_markers_and_the_via_graph() {
        let parsed = parse(COMPILED, Path::new("requirements.txt")).unwrap();
        assert_eq!(parsed.python.as_deref(), Some("3.13"));
        assert_eq!(parsed.index_url.as_deref(), Some("https://mirror.example/simple"));
        let doc = sbom(COMPILED, "linux-64");
        let names: Vec<&str> = doc.packages.iter().map(|p| p.name.as_str()).collect();
        assert_eq!(names, ["certifi", "idna", "requests"], "pywin32 is for win32 only");
        let requests = doc.packages.iter().find(|p| p.name == "requests").unwrap();
        assert_eq!(requests.purl, "pkg:pypi/requests@2.32.3");
        assert_eq!(requests.sha256.as_deref(), Some("ee"));
        assert_eq!(
            requests.dependencies,
            ["pkg:pypi/certifi@2026.7.22", "pkg:pypi/idna@3.20"]
        );
        assert_eq!(requests.properties[crate::manifest::DIRECT_PROPERTY], "true");
        assert_eq!(requests.supplier.as_ref().unwrap().name, "mirror.example");
        let certifi = doc.packages.iter().find(|p| p.name == "certifi").unwrap();
        assert_eq!(certifi.sha256.as_deref(), Some("aa"), "the first hash, lower-cased");
        assert!(!certifi.properties.contains_key(crate::manifest::DIRECT_PROPERTY));
        assert!(doc.declared_roots);
        assert_eq!(crate::format::top_level_ids(&doc), ["pkg:pypi/requests@2.32.3"]);

        let windows = sbom(COMPILED, "win-64");
        let pywin32 = windows.packages.iter().find(|p| p.name == "pywin32").unwrap();
        assert_eq!(pywin32.properties["pixi:marker"], "sys_platform == 'win32'");
        assert_eq!(pywin32.properties[crate::manifest::DIRECT_PROPERTY], "true");
    }

    #[test]
    fn anything_not_pinned_is_refused_with_the_line() {
        for (text, line) in [
            ("requests>=2.31\n", 1),
            ("idna==3.20\nrequests\n", 2),
            ("django==5.*\n", 1),
            ("requests==2.32.3,<3\n", 1),
            ("pkg @ https://example.com/pkg.tar.gz\n", 1),
            ("idna==3.20\n-e ./libs/local\n", 2),
        ] {
            match parse(text, Path::new("requirements.txt")) {
                Err(RequirementsError::NotPinned { line: got, .. }) => assert_eq!(got, line, "{text}"),
                other => panic!("{text}: {other:?}"),
            }
        }
        assert!(matches!(
            parse("not a requirement!\n", Path::new("r.txt")),
            Err(RequirementsError::Parse { line: 1, .. })
        ));
        assert!(parse("requests===2.32.3 # an exact pin\n", Path::new("r.txt")).is_ok());
    }

    #[test]
    fn includes_are_followed_once_and_files_are_recognised() {
        let dir = tempfile::tempdir().unwrap();
        std::fs::write(dir.path().join("base.txt"), "idna==3.20\n-r requirements.txt\n").unwrap();
        std::fs::write(dir.path().join("requirements.txt"), "-r base.txt\nrequests==2.32.3\n").unwrap();
        let loaded = load(&dir.path().join("requirements.txt")).unwrap();
        let names: Vec<&str> = loaded.requirements.pins.iter().map(|p| p.name.as_str()).collect();
        assert_eq!(names, ["idna", "requests"], "the cycle is followed once");
        assert!(load(&dir.path().join("missing.txt")).is_err());
        std::fs::write(dir.path().join("broken.txt"), "-r nowhere.txt\n").unwrap();
        assert!(matches!(
            load(&dir.path().join("broken.txt")),
            Err(RequirementsError::Read { .. })
        ));

        assert!(is_requirements(&dir.path().join("requirements.txt")));
        std::fs::write(dir.path().join("requirements-dev.txt"), "pytest>=8\n").unwrap();
        assert!(
            is_requirements(&dir.path().join("requirements-dev.txt")),
            "named for it, so read and refused"
        );
        std::fs::write(dir.path().join("prod.txt"), "requests==2.32.3\n").unwrap();
        assert!(is_requirements(&dir.path().join("prod.txt")), "pins something");
        std::fs::write(dir.path().join("notes.txt"), "hello\n").unwrap();
        assert!(
            !is_requirements(&dir.path().join("notes.txt")),
            "a word is not a requirements file"
        );
        for (name, text) in [
            ("explicit.txt", "@EXPLICIT\nhttps://conda.anaconda.org/x.conda\n"),
            ("notes.txt", "{\"json\": true}\n"),
            ("requirements-empty.txt", "# only comments\n"),
            ("pixi.lock", "version: 6\n"),
        ] {
            std::fs::write(dir.path().join(name), text).unwrap();
            assert!(!is_requirements(&dir.path().join(name)), "{name}");
        }
        assert!(!is_requirements(&dir.path().join("absent-requirements.txt")));
    }
}
