//! `--verify-files` and `--report files`: hash what each conda package installed and compare it
//! with what its `conda-meta` record says was installed (#455). syft records file digests but
//! compares them with nothing; conda-meta already holds the expected SHA-256 of every file, so an
//! installed environment can be checked against itself, offline.
//!
//! The expected hash is `sha256_in_prefix` where the installer rewrote the file (a prefix
//! placeholder, an entry point), else the package's own `sha256`. Python rewrites its own
//! bytecode caches when it decides they are stale, so a changed or missing `.pyc` is counted as
//! regenerated bytecode and never fails the run.

use std::collections::BTreeMap;
use std::io::Read;
use std::path::Path;

use rayon::prelude::*;
use serde::Deserialize;
use sha2::{Digest, Sha256};

use crate::model::{PackageKind, Sbom};

/// Exit code when `--verify-files` or `--report files` finds a modified or missing file.
pub const MODIFIED_EXIT_CODE: i32 = 11;

/// The files of a package whose contents differ from its conda-meta record, comma-separated.
pub const MODIFIED_PROPERTY: &str = "pixi:modified-files";
/// The files of a package its conda-meta record lists that are not on disk, comma-separated.
pub const MISSING_PROPERTY: &str = "pixi:missing-files";
/// How many of a package's files were checked.
pub const VERIFIED_PROPERTY: &str = "pixi:verified-files";
/// How many of a package's `.pyc` files Python has rewritten or removed since installation.
pub const BYTECODE_PROPERTY: &str = "pixi:regenerated-bytecode";

#[derive(Debug, Deserialize)]
struct Record {
    name: String,
    version: String,
    build: String,
    #[serde(default)]
    paths_data: PathsData,
}

#[derive(Debug, Default, Deserialize)]
struct PathsData {
    #[serde(default)]
    paths: Vec<PathEntry>,
}

#[derive(Debug, Deserialize)]
struct PathEntry {
    #[serde(rename = "_path")]
    path: String,
    #[serde(default)]
    path_type: Option<String>,
    #[serde(default)]
    sha256: Option<String>,
    #[serde(default)]
    sha256_in_prefix: Option<String>,
}

/// What became of one installed file.
#[derive(Debug, Clone, Copy, PartialEq, Eq, PartialOrd, Ord)]
pub enum State {
    Modified,
    Missing,
    /// A `.pyc` Python rewrote or removed; reported, never a failure.
    Bytecode,
}

/// The outcome for one conda package.
#[derive(Debug, Clone, Default, PartialEq, Eq)]
pub struct Verified {
    pub checked: usize,
    pub modified: Vec<String>,
    pub missing: Vec<String>,
    pub bytecode: usize,
}

/// Check every file every conda-meta record under `prefix` lists, keyed by (name, version, build).
/// A record that cannot be read is skipped (building the document has already reported it), and
/// so is one with no `paths_data`.
pub fn verify(prefix: &Path) -> BTreeMap<(String, String, String), Verified> {
    let records: Vec<Record> = std::fs::read_dir(prefix.join("conda-meta"))
        .into_iter()
        .flatten()
        .flatten()
        .map(|entry| entry.path())
        .filter(|path| path.extension().is_some_and(|e| e == "json"))
        .filter_map(|path| serde_json::from_str::<Record>(&std::fs::read_to_string(path).ok()?).ok())
        // An installer that wrote no paths_data left nothing to check against.
        .filter(|record| !record.paths_data.paths.is_empty())
        .collect();
    records
        .into_par_iter()
        .map(|record| {
            let mut verified = Verified::default();
            let states: Vec<(String, Option<State>)> = record
                .paths_data
                .paths
                .par_iter()
                .filter_map(|entry| Some((entry.path.clone(), check(prefix, entry)?)))
                .collect();
            for (path, state) in states {
                verified.checked += 1;
                match state {
                    None => {}
                    Some(State::Modified) => verified.modified.push(path),
                    Some(State::Missing) => verified.missing.push(path),
                    Some(State::Bytecode) => verified.bytecode += 1,
                }
            }
            verified.modified.sort();
            verified.missing.sort();
            ((record.name, record.version, record.build), verified)
        })
        .collect()
}

/// `None` when the entry cannot be checked (no expected hash), `Some(None)` when it matches.
fn check(prefix: &Path, entry: &PathEntry) -> Option<Option<State>> {
    let path = prefix.join(&entry.path);
    let bytecode = entry.path.ends_with(".pyc");
    let changed = |state| Some(Some(if bytecode { State::Bytecode } else { state }));
    match entry.path_type.as_deref() {
        // A link's target is another entry, checked in its own right.
        Some("softlink") => {
            return if path.symlink_metadata().is_ok() {
                Some(None)
            } else {
                changed(State::Missing)
            };
        }
        Some("directory") => {
            return if path.is_dir() {
                Some(None)
            } else {
                changed(State::Missing)
            };
        }
        _ => {}
    }
    let expected = entry.sha256_in_prefix.as_deref().or(entry.sha256.as_deref())?;
    match sha256(&path) {
        Ok(actual) if actual.eq_ignore_ascii_case(expected) => Some(None),
        Ok(_) => changed(State::Modified),
        Err(error) if error.kind() == std::io::ErrorKind::NotFound => changed(State::Missing),
        // Unreadable is not the same as tampered with, but it cannot be vouched for either.
        Err(_) => changed(State::Modified),
    }
}

fn sha256(path: &Path) -> std::io::Result<String> {
    let mut file = std::fs::File::open(path)?;
    let mut hasher = Sha256::new();
    let mut buffer = vec![0; 1 << 16];
    loop {
        let read = file.read(&mut buffer)?;
        if read == 0 {
            break;
        }
        hasher.update(&buffer[..read]);
    }
    Ok(hasher.finalize().iter().map(|byte| format!("{byte:02x}")).collect())
}

/// Record each conda package's outcome in its properties. Returns how many files were modified
/// or missing across the document.
pub fn attach(sbom: &mut Sbom, results: &BTreeMap<(String, String, String), Verified>) -> usize {
    let mut failing = 0;
    for package in &mut sbom.packages {
        if package.kind != PackageKind::CondaBinary {
            continue;
        }
        let key = (
            package.name.clone(),
            package.version.clone().unwrap_or_default(),
            package.properties.get("pixi:build").cloned().unwrap_or_default(),
        );
        let Some(verified) = results.get(&key) else {
            continue;
        };
        failing += verified.modified.len() + verified.missing.len();
        let properties = &mut package.properties;
        properties.insert(VERIFIED_PROPERTY.into(), verified.checked.to_string());
        if !verified.modified.is_empty() {
            properties.insert(MODIFIED_PROPERTY.into(), verified.modified.join(", "));
        }
        if !verified.missing.is_empty() {
            properties.insert(MISSING_PROPERTY.into(), verified.missing.join(", "));
        }
        if verified.bytecode > 0 {
            properties.insert(BYTECODE_PROPERTY.into(), verified.bytecode.to_string());
        }
    }
    failing
}

#[cfg(test)]
mod tests {
    use super::*;

    fn digest(bytes: &[u8]) -> String {
        Sha256::digest(bytes).iter().map(|byte| format!("{byte:02x}")).collect()
    }

    fn environment() -> tempfile::TempDir {
        let dir = tempfile::tempdir().unwrap();
        let root = dir.path();
        std::fs::create_dir_all(root.join("conda-meta")).unwrap();
        std::fs::create_dir_all(root.join("lib/__pycache__")).unwrap();
        std::fs::create_dir_all(root.join("bin")).unwrap();
        std::fs::write(root.join("lib/libz.so"), b"zlib").unwrap();
        std::fs::write(root.join("lib/zlib.h"), b"header").unwrap();
        std::fs::write(root.join("bin/tool"), b"#!/opt/env/bin/python").unwrap();
        std::fs::write(root.join("lib/__pycache__/m.cpython-312.pyc"), b"rewritten").unwrap();
        let record = serde_json::json!({
            "name": "zlib", "version": "1.3.1", "build": "h0",
            "paths_data": {"paths": [
                {"_path": "lib/libz.so", "path_type": "hardlink", "sha256": digest(b"zlib")},
                {"_path": "lib/zlib.h", "path_type": "hardlink", "sha256": digest(b"original")},
                {"_path": "lib/gone.a", "path_type": "hardlink", "sha256": digest(b"gone")},
                {"_path": "bin/tool", "path_type": "hardlink", "sha256": digest(b"#!/placeholder/bin/python"),
                 "sha256_in_prefix": digest(b"#!/opt/env/bin/python")},
                {"_path": "lib/__pycache__/m.cpython-312.pyc", "path_type": "hardlink", "sha256": digest(b"compiled")},
                {"_path": "lib/__pycache__/n.cpython-312.pyc", "path_type": "hardlink", "sha256": digest(b"compiled")},
                {"_path": "lib/no-hash", "path_type": "hardlink"}
            ]}
        });
        std::fs::write(root.join("conda-meta/zlib-1.3.1-h0.json"), record.to_string()).unwrap();
        std::fs::write(root.join("conda-meta/broken-1.0-0.json"), "{").unwrap();
        std::fs::write(
            root.join("conda-meta/bare-1.0-0.json"),
            r#"{"name":"bare","version":"1.0","build":"0"}"#,
        )
        .unwrap();
        dir
    }

    #[test]
    fn altered_and_missing_files_are_found_and_bytecode_is_set_apart() {
        let dir = environment();
        let results = verify(dir.path());
        assert_eq!(
            results.len(),
            1,
            "an unreadable record, and one with no paths_data, are skipped"
        );
        let zlib = &results[&("zlib".into(), "1.3.1".into(), "h0".into())];
        assert_eq!(zlib.checked, 6, "an entry with no hash cannot be checked");
        assert_eq!(zlib.modified, ["lib/zlib.h"]);
        assert_eq!(zlib.missing, ["lib/gone.a"]);
        assert_eq!(zlib.bytecode, 2, "a rewritten and a removed .pyc");
    }

    #[test]
    fn an_unaltered_environment_reports_nothing() {
        let dir = environment();
        std::fs::write(dir.path().join("lib/zlib.h"), b"original").unwrap();
        std::fs::write(dir.path().join("lib/gone.a"), b"gone").unwrap();
        let zlib = &verify(dir.path())[&("zlib".into(), "1.3.1".into(), "h0".into())];
        assert!(zlib.modified.is_empty() && zlib.missing.is_empty(), "{zlib:?}");
    }

    #[cfg(unix)]
    #[test]
    fn links_and_directories_are_checked_for_presence() {
        let dir = tempfile::tempdir().unwrap();
        let root = dir.path();
        std::fs::create_dir_all(root.join("conda-meta")).unwrap();
        std::fs::create_dir_all(root.join("share/empty")).unwrap();
        std::os::unix::fs::symlink("nowhere", root.join("lib-link")).unwrap();
        let record = serde_json::json!({
            "name": "a", "version": "1", "build": "0",
            "paths_data": {"paths": [
                {"_path": "lib-link", "path_type": "softlink"},
                {"_path": "other-link", "path_type": "softlink"},
                {"_path": "share/empty", "path_type": "directory"},
            ]}
        });
        std::fs::write(root.join("conda-meta/a-1-0.json"), record.to_string()).unwrap();
        let a = &verify(root)[&("a".into(), "1".into(), "0".into())];
        assert_eq!(a.checked, 3);
        assert_eq!(
            a.missing,
            ["other-link"],
            "a dangling link is still the link conda made"
        );
    }

    #[test]
    fn outcomes_become_properties_of_the_matching_conda_package() {
        let dir = environment();
        let results = verify(dir.path());
        let mut sbom = crate::format::testing::sample_sbom();
        let zlib = sbom.packages.iter_mut().find(|p| p.name == "zlib").unwrap();
        zlib.kind = PackageKind::CondaBinary;
        zlib.version = Some("1.3.1".into());
        zlib.properties.insert("pixi:build".into(), "h0".into());
        assert_eq!(attach(&mut sbom, &results), 2);
        let zlib = sbom.packages.iter().find(|p| p.name == "zlib").unwrap();
        assert_eq!(zlib.properties[VERIFIED_PROPERTY], "6");
        assert_eq!(zlib.properties[MODIFIED_PROPERTY], "lib/zlib.h");
        assert_eq!(zlib.properties[MISSING_PROPERTY], "lib/gone.a");
        assert_eq!(zlib.properties[BYTECODE_PROPERTY], "2");
        let others = sbom.packages.iter().filter(|p| p.name != "zlib");
        assert!(
            others
                .into_iter()
                .all(|p| !p.properties.contains_key(VERIFIED_PROPERTY))
        );
    }
}
